---
title: "Results from GWAMA random AFR & EUR"
author: "Alex Flynn-Carroll"
date: "2026-01-05"
output: html_document
---

###############################################################################################
# library
###############################################################################################

```{r packages}

library(tidyverse)
library(dplyr)
library(data.table)
library(ggplot2)
library(qqman)
library(PheWAS)
library(jpeg)
library(wesanderson)
library(ggrepel)
library(circlize)

```

###############################################################################################
# read in rolled up df
###############################################################################################

```{r}

phe_367.2 <- read.table("/mnt/arcus/lab/users/flynncarra/projects/20260105_GWAMA_random/GWAMA_output//ae_results_phe_367.2.gwama.out", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

phe_1002 <- read.table("/mnt/arcus/lab/users/flynncarra/projects/20260105_GWAMA_random/GWAMA_output//ae_results_phe_1002.gwama.out", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

```

```{r}

# 1. List all files ending with "allchr.txt" in a folder
file_list <- list.files(path = "/mnt/arcus/lab/users/flynncarra/projects/20260105_GWAMA_random/GWAMA_output/", pattern = "\\gwama.out$", full.names = TRUE)

```

```{r}

# 2. Read each file into a list of data frames
df_list <- lapply(file_list, function(f) {
  df <- read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
  df <- subset(df, p.value < 0.01)
  df$source_file <- basename(f)
  df
})

# 3. Combine all data frames into one
res <- do.call(rbind, df_list)

rm(df_list)

```


###############################################################################################
# filter res
###############################################################################################

```{r}

res_og <- res

```

```{r}

dim(res)

res <- res %>%
  filter(!grepl("\\?", effects))

dim(res)

```

[1] 1210769      18
[1] 857860     18

###############################################################################################
# Phecodes
###############################################################################################

```{r icd to phecode map}

phecode_map <- read.csv("../20250801_arcus_phenotype_counts/Phecode_map_v1_2_icd9_icd10cm.csv")

```

```{r unique phecode descriptions}

phecodes <- unique(phecode_map[,c("Phecode", "PhecodeString")])

phecodes <- phecodes %>%
  group_by(Phecode) %>%
  summarise(
    PhecodeString = paste(unique(PhecodeString), collapse = "; "),
    .groups = "drop"
  )

colnames(phecodes) <- c("phecode", "PhecodeString")

phecodes$phecode <- as.character(phecodes$phecode)

```

```{r}

res$phecode <- str_extract(
  res$source_file,
  "(?<=ae_results_phe_)[0-9.]+(?=\\.gwama\\.out)"
)


```

###############################################################################################
# plot phewas
###############################################################################################

```{r}

filtered_phe_man_phe <- phewasManhattan(data.frame(phenotype = res$phecode, p = res$p.value), 
                                    title = "Arcus AFR-EUR Random Effects Meta; Phecodes", 
                                    annotate.size=2,
                                    size.x.labels=5, 
                                    size.y.labels=5,
                                    significant.line = 5e-8,
                                    point.size =1)+ coord_cartesian(ylim = c(2, NA))

filtered_phe_man_phe

```
