---
title: "Updated HM3 PheWAS results"
output: html_document
date: "2025-11-04"
---

###############################################################################################
# library
###############################################################################################

```{r packages}

library(tidyverse)
library(dplyr)
library(data.table)
library(ggplot2)
library(qqman)
library(PheWAS)
library(jpeg)

```

###############################################################################################
# read in data
###############################################################################################

```{r}

# 1. List all files ending with "allchr.txt" in a folder
file_list <- list.files(path = "/mnt/arcus/lab/users/flynncarra/projects/20251103_saige_hm3_comb/results/", pattern = "top_phe_[0-9]+_allchr\\.txt$", full.names = TRUE)

# 2. Read each file into a list of data frames
df_list <- lapply(file_list, function(f) {
  df <- read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
  df <- subset(df, p.value < 0.01)
  df$source_file <- basename(f)
  df
})

# 3. Combine all data frames into one
res <- do.call(rbind, df_list)

rm(df_list)

```

```{r}

# 1. List all files ending with "allchr.txt" in a folder
file_list_phe <- list.files(path = "/mnt/arcus/lab/users/flynncarra/projects/20251103_saige_hm3_comb/results/", pattern = "^phe_[0-9]+(\\.[0-9]+)?_allchr\\.txt$", full.names = TRUE)

# 2. Read each file into a list of data frames
df_list <- lapply(file_list_phe, function(f) {
  df <- read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
  df <- subset(df, p.value < 0.01)
  df$source_file <- basename(f)
  df
})

# 3. Combine all data frames into one
res_phe <- do.call(rbind, df_list)

rm(df_list)

```

###############################################################################################
# plot phecode results
###############################################################################################

```{r}

res_phe <- res_phe[res_phe$source_file != "phe_604.1_allchr.txt",] 


```


```{r}

res_phe$phecode <- str_extract(res_phe$source_file, "(?<=phe_).*?(?=_allchr\\.txt)")

```

```{r}

top_hits_phe <- res_phe[res_phe$p.value<=5e-7,]

```

```{r}

filtered_phe_man_phe <- phewasManhattan(data.frame(phenotype = res_phe$phecode, p = res_phe$p.value), 
                                    annotate.angle=45, 
                                    title = "Arcus EUR HM3 Phecodes", 
                                    annotate.size=2,
                                    size.x.labels=5, size.y.labels=5,
                                    significant.line = 5e-8)+ coord_cartesian(ylim = c(2, 9))

```

```{r}

# Save as JPEG, specify size in inches
jpeg(
  filename = "HM3_var_phewas_gws_5e7_v2.jpg",
  width = 8,        # width in inches
  height = 4,       # height in inches
  units = "in",     # tells R that width/height are in inches
  res = 300         # resolution in DPI (dots per inch)
)

# Your plot
filtered_phe_man_phe

# Important: close the device to finalize the file
dev.off()

```

```{r}

write_csv(top_hits_phe, "top_hits_hm3_v2.csv")

```

###############################################################################################
# plot updated phecode results
###############################################################################################

```{r}

res <- res[res$source_file != "top_phe_604_allchr.txt",]

```


```{r}

res$phecode <- str_extract(res$source_file, "(?<=top_phe_).*?(?=_allchr\\.txt)")

```

```{r}

top_hits <- res[res$p.value<=5e-7,]

```

```{r}

top_hits <- left_join(top_hits, )

```

```{r}

filtered_phe_man <- phewasManhattan(data.frame(phenotype = res$phecode, p = res$p.value), 
                                    annotate.angle=45, 
                                    title = "Arcus EUR HM3 Top Phecodes", 
                                    annotate.size=2,
                                    size.x.labels=5, size.y.labels=5,
                                    significant.line = 5e-7)+ coord_cartesian(ylim = c(2, 9))

```

```{r}

# Save as JPEG, specify size in inches
jpeg(
  filename = "HM3_var_phewas_gws_5e7_topl.jpg",
  width = 8,        # width in inches
  height = 4,       # height in inches
  units = "in",     # tells R that width/height are in inches
  res = 300         # resolution in DPI (dots per inch)
)

# Your plot
filtered_phe_man

# Important: close the device to finalize the file
dev.off()

```

```{r}

# Open a new plotting window 7 inches wide and 5 inches tall
windows(width = 8, height = 4)

# Example plot
filtered_phe_man


```

```{r}

write_csv(top_hits, "top_hits_hm3_topl.csv")

```

```{r}

# Read the image
img <- readJPEG("HM3_var_phewas_gws_5e7_topl.jpg")  # path to your JPEG

# Display in R plot window
grid::grid.raster(img)


```