---
title: "Results from the blood phewas with paper covariates"
author: "Alex Flynn-Carroll"
date: "2025-11-24"
output: html_document
---

###############################################################################################
# library
###############################################################################################

```{r packages}

library(tidyverse)
library(dplyr)
library(data.table)
library(ggplot2)
library(qqman)
library(PheWAS)
library(jpeg)
library(wesanderson)
library(ggrepel)
library(circlize)

```

###############################################################################################
# read in data
###############################################################################################

```{r}

max_rbc <- read.table("/home/flynncarra/projects/20251123_blood_gwas/results/max_RBC_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)


```

```{r}

mean_rbc <- read.table("/home/flynncarra/projects/20251123_blood_gwas/results/mean_RBC_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

mean_rbc$phenotype <- "mean RBC"
```

```{r}

median_rbc <- read.table("/home/flynncarra/projects/20251123_blood_gwas/results/median_RBC_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)


```

```{r}

min_rbc <- read.table("/home/flynncarra/projects/20251123_blood_gwas/results/min_RBC_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)


```

```{r}

max_wbc <- read.table("/home/flynncarra/projects/20251123_blood_gwas/results/max_WBC_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)


```

```{r}

mean_wbc <- read.table("/home/flynncarra/projects/20251123_blood_gwas/results/mean_WBC_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)


```

```{r}

median_wbc <- read.table("/home/flynncarra/projects/20251123_blood_gwas/results/median_WBC_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)


```

```{r}

min_wbc <- read.table("/home/flynncarra/projects/20251123_blood_gwas/results/min_WBC_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)


```

###############################################################################################
# manhattan plots
###############################################################################################

```{r}

man_mean_rbc  <- manhattan(mean_rbc,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Mean RBC")
#          ylim = c(0, max(-log10(phe_751.12$p.value)) + 1))
```

```{r}

chisq_mean_rbc <- qchisq(1 - mean_rbc$p.value, 1)
lambda_gc_mean_rbc <- median(chisq_mean_rbc) / qchisq(0.5, 1)
lambda_gc_mean_rbc


```

```{r}

qq(mean_rbc$p.value, main = sprintf("Mean RBC: EUR (λ = %.3f)", lambda_gc_mean_rbc))


```

```{r}

man_median_rbc  <- manhattan(median_rbc,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Median RBC")
#          ylim = c(0, max(-log10(phe_751.12$p.value)) + 1))
```

```{r}

man_max_rbc  <- manhattan(max_rbc,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Max RBC")
#          ylim = c(0, max(-log10(phe_751.12$p.value)) + 1))
```

```{r}

man_min_rbc  <- manhattan(min_rbc,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Min RBC")
#          ylim = c(0, max(-log10(phe_751.12$p.value)) + 1))
```


```{r}

man_mean_wbc  <- manhattan(mean_wbc,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Mean WBC")
#          ylim = c(0, max(-log10(phe_751.12$p.value)) + 1))
```

```{r}

man_max_wbc  <- manhattan(max_wbc,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Max WBC")
#          ylim = c(0, max(-log10(phe_751.12$p.value)) + 1))
```

```{r}

man_min_wbc  <- manhattan(min_wbc,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Min WBC")
#          ylim = c(0, max(-log10(phe_751.12$p.value)) + 1))
```

```{r}

man_median_wbc  <- manhattan(median_wbc,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Median WBC")
#          ylim = c(0, max(-log10(phe_751.12$p.value)) + 1))
```