---
title: "Root Phecode shared variant SAIGE PheWAS"
author: "Alex Flynn-Carroll"
date: "2025-11-13"
output: html_document
---

###############################################################################################
# library
###############################################################################################

```{r packages}

library(tidyverse)
library(dplyr)
library(data.table)
library(ggplot2)
library(qqman)
library(PheWAS)
library(jpeg)
library(wesanderson)
library(ggrepel)
library(circlize)

```

###############################################################################################
# read in data
###############################################################################################

```{r}

# 1. List all files ending with "allchr.txt" in a folder
file_list <- list.files(path = "/mnt/arcus/lab/users/flynncarra/projects/20251112_saige_root_shared_var/results/",
                        pattern = "^phe_[0-9]+(\\.[0-9]+)?_allchr\\.txt$", full.names = TRUE)

# 2. Read each file into a list of data frames
df_list <- lapply(file_list, function(f) {
  df <- read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
  df <- subset(df, p.value < 0.01)
  df$source_file <- basename(f)
  df
})

# 3. Combine all data frames into one
res <- do.call(rbind, df_list)

rm(df_list)

```

phe_313_allchr.txt
```{r}

dvp_res <- read.table("/mnt/arcus/lab/users/flynncarra/projects/20251112_saige_root_shared_var/results/phe_313_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

```

```{r}

inm_res <- read.table("/mnt/arcus/lab/users/flynncarra/projects/20251112_saige_root_shared_var/results/phe_557_allchr.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

```


```{r icd to phecode map}

phecode_map <- read.csv("../20250801_arcus_phenotype_counts/Phecode_map_v1_2_icd9_icd10cm.csv")

```

###############################################################################################
# Phecodes
###############################################################################################

```{r unique phecode descriptions}

phecodes <- unique(phecode_map[,c("Phecode", "PhecodeString")])

phecodes <- phecodes %>%
  group_by(Phecode) %>%
  summarise(
    PhecodeString = paste(unique(PhecodeString), collapse = "; "),
    .groups = "drop"
  )

colnames(phecodes) <- c("phecode", "PhecodeString")

phecodes$phecode <- as.character(phecodes$phecode)

```

###############################################################################################
# plot results
###############################################################################################

```{r}

res$phecode <- str_extract(res$source_file, "(?<=phe_).*?(?=_allchr\\.txt)")

```

```{r}

res <- res[res$source_file != "phe_604_allchr.txt",] 

```

```{r}

top_hits <- res[res$p.value<=5e-8,]
top_hits <- left_join(top_hits, phecodes, by="phecode")

```


```{r}

top_hits_save <- top_hits[,c("MarkerID", "AF_Allele2", "BETA", "SE", "p.value", "N_case", "N_ctrl", "phecode", "PhecodeString")]

```

```{r}

write_csv(top_hits_save, "shared_var_root_phewas_saige.csv")

```

```{r}

write_csv(top_hits, "shared_var_root_phewas_saige.csv")

```

```{r}

filtered_phe_man_phe <- phewasManhattan(data.frame(phenotype = res$phecode, p = res$p.value), 
                                   # annotate.angle=45, 
                                    title = "Arcus EUR Shared Variants; Root Phecodes", 
                                    annotate.size=2,
                                    size.x.labels=5, 
                                    size.y.labels=5,
                                    significant.line = 5e-8,
                                    point.size =1)+ coord_cartesian(ylim = c(2, NA))

```

```{r}

# Save as JPEG, specify size in inches
jpeg(
  filename = "shared_var_phewas_gws_5e8_v2.jpg",
  width = 8,        # width in inches
  height = 4,       # height in inches
  units = "in",     # tells R that width/height are in inches
  res = 300         # resolution in DPI (dots per inch)
)

# Your plot
filtered_phe_man_phe

# Important: close the device to finalize the file
dev.off()

```

###############################################################################################
# GWAS Plots
###############################################################################################

####################### Intestinal Malabsorption 

```{r}

qq(inm_res$p.value, main = "QQ plot for EUR Intestinal Malabsorption (557)")


```

```{r}

chisq_inm <- qchisq(1 - inm_res$p.value, 1)
lambda_gc_inm <- median(chisq_inm) / qchisq(0.5, 1)
lambda_gc_inm


```


```{r}

jpeg("INM_QQ.jpg", width = 1200, height = 1200, res = 150)
qq(inm_res$p.value, main = "QQ plot for EUR Intestinal Malabsorption (557)")
dev.off()


```


```{r}

inm_man <- manhattan(inm_res,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Intestinal Malabsorption (557)",
          ylim = c(0, max(-log10(inm_res$p.value)) + 1))

inm_man

```


```{r}

jpeg("inm_man.jpg", width = 8*300, height = 6*300, res = 300)
 manhattan(inm_res,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Intestinal Malabsorption (557)",
          ylim = c(0, max(-log10(inm_res$p.value)) + 1))

dev.off()


```

####################### Pervasive developmental disorders

```{r}

qq(dvp_res$p.value, main = "QQ plot for EUR Pervasive developmental disorders (313)")


```

```{r}

chisq_dvp <- qchisq(1 - dvp_res$p.value, 1)
lambda_gc_dvp <- median(chisq_dvp) / qchisq(0.5, 1)
lambda_gc_dvp


```

```{r}

jpeg("DVP_QQ.jpg", width = 1200, height = 1200, res = 150)
qq(dvp_res$p.value, main = "QQ plot for EUR Pervasive developmental disorders (313)")
dev.off()


```

```{r}

dvp_man <- manhattan(dvp_res,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Pervasive developmental disorders (313))",
          ylim = c(0, max(-log10(dvp_res$p.value)) + 1))

dvp_man

```

```{r}

jpeg("dvp_man.jpg", width = 8*300, height = 6*300, res = 300)
manhattan(dvp_res,
          chr = "CHR",
          bp = "POS",
          snp = "MarkerID",
          p = "p.value",
          main = "Manhattan Plot: EUR Pervasive developmental disorders (313))",
          ylim = c(0, max(-log10(dvp_res$p.value)) + 1))

dev.off()


```