---
title: "PheWAS results from shared var PLINK2 PheWAS"
output: html_document
date: "2025-11-10"
---


###############################################################################################
# library
###############################################################################################

```{r packages}

library(tidyverse)
library(dplyr)
library(data.table)
library(ggplot2)
library(qqman)
library(PheWAS)
library(jpeg)

```

###############################################################################################
# read in data
###############################################################################################

```{r}

test_df <- read.table("/mnt/arcus/lab/users/flynncarra/projects/20251110_plink2_phewas_shared_var/results/eur_phe_495.phe_495.glm.logistic.hybrid", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

colnames(test_df) <- c("CHROM", "POS", "ID", "REF", "ALT", "PROVISIONAL_REF?", "A1", "OMITTED", "A1_FREQ", "FIRTH?", "TEST", "OBS_CT", "OR", "LOG(OR)_SE", "Z_STAT", "P", "ERRCODE")

```

```{r}

file_list <- list.files(
  path = "/mnt/arcus/lab/users/flynncarra/projects/20251110_plink2_phewas_shared_var/results/",
  pattern = "^eur_phe_[0-9]+(?:\\.[0-9]+)*\\.phe_[0-9]+(?:\\.[0-9]+)*\\.glm\\.logistic\\.hybrid$",
  full.names = TRUE
)

```

```{r read in results}

df_list <- lapply(file_list, function(f) {
  df <- read.table(f, header = F, sep = "\t", stringsAsFactors = FALSE)
  colnames(df) <- c("CHROM", "POS", "ID", "REF", "ALT", "PROVISIONAL_REF?", "A1", "OMITTED", "A1_FREQ", "FIRTH?", "TEST", "OBS_CT", "OR", "LOG(OR)_SE", "Z_STAT", "P", "ERRCODE")
  df <- subset(df, TEST == "ADD")
  df <- subset(df, P < 0.01)
  df$source_file <- basename(f)
  df
})

# Combine all data frames into one
res <- do.call(rbind, df_list)

rm(df_list)

```

```{r}

View(res[res$P <5e-6,])

```

```{r}

phenos_run <- read.table("/mnt/arcus/lab/users/flynncarra/projects/20251106_plink2_files/phecodes_200_v2.txt")

```

```{r icd to phecode map}

phecode_map <- read.csv("../20250801_arcus_phenotype_counts/Phecode_map_v1_2_icd9_icd10cm.csv")

```

###############################################################################################
# Phecodes
###############################################################################################

```{r unique phecode descriptions}

phecodes <- unique(phecode_map[,c("Phecode", "PhecodeString")])

phecodes <- phecodes %>%
  group_by(Phecode) %>%
  summarise(
    PhecodeString = paste(unique(PhecodeString), collapse = "; "),
    .groups = "drop"
  )

colnames(phecodes) <- c("phecode", "PhecodeString")

phecodes$phecode <- as.character(phecodes$phecode)

```

###############################################################################################
# see failed phenos
###############################################################################################

```{r}

#completed_phenos <- sub("^eur_(.*?)\\.phe.*", "\\1", unique(res$source_file))

completed_phenos <- sub(".*eur_(.*?)\\.phe.*", "\\1", unique(file_list))

```

sub(".*eur_phe_(.*?)\\.phe.*", "\\1", unique(file_list))

```{r}

setdiff(unlist(phenos_run), completed_phenos)

```

###############################################################################################
# get rsids
###############################################################################################

```{r}

vars <- unique(test_df[,c("CHROM", "POS", "ID", "REF", "ALT")])

```

```{r}

chr22 <- read.table(gzfile("/mnt/arcus/lab/users/flynncarra/projects/20251110_plink2_shared_var_results/rsid_hg19/bed_chr_22.bed.gz"), header = F, sep = "\t", skip = 1)


```

###############################################################################################
# get rsids
###############################################################################################

```{r}

res$phecode <- sub(".*eur_phe_(.*?)\\.phe.*", "\\1", res$source_file)

```

```{r}

top_hits <- res[res$P<=5e-8,]
top_hits <- left_join(top_hits, phecodes, by="phecode")

```


```{r}

top_hits_save <- top_hits[,c("ID", "A1_FREQ", "OR", "P", "OBS_CT", "phecode", "PhecodeString")]

```

```{r}

write_csv(top_hits_save, "shared_var_phewas_plink2.csv")

```

```{r}

filtered_phe_man <- phewasManhattan(data.frame(phenotype = res$phecode, p = res$P), 
                                   # annotate.angle=45, 
                                    title = "Arcus EUR Shared Variants; PLINK2", 
                                    annotate.size=2,
                                    size.x.labels=5, 
                                    size.y.labels=5,
                                    significant.line = 5e-8,
                                    point.size =1)+ coord_cartesian(ylim = c(2, NA))



```

```{r}

# Save as JPEG, specify size in inches
jpeg(
  filename = "shared_var_plink2_gws_5e8_v2.jpg",
  width = 8,        # width in inches
  height = 4,       # height in inches
  units = "in",     # tells R that width/height are in inches
  res = 300         # resolution in DPI (dots per inch)
)

# Your plot
filtered_phe_man

# Important: close the device to finalize the file
dev.off()

```

```{r}

write_csv(top_hits, "top_hits_shared_var_phewas.csv")

```